// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Partnerly.Models;

#nullable disable

namespace Partnerly.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250922064528_createdTheEmailServices")]
    partial class createdTheEmailServices
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Partnerly.Models.EmailAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EmailAttachments");
                });

            modelBuilder.Entity("Partnerly.Models.EmailConfirmationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid?>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Used")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("EmailConfirmationTokens");
                });

            modelBuilder.Entity("Partnerly.Models.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttachmentsMeta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyPlain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("73630857-0cd2-49bf-83cf-5a823d8b5fb0"),
                            BodyHtml = "\r\n                            <h2>Здравствуйте, {{UserName}}!</h2>\r\n                            <p>\r\n                                Подтвердите ваш email, перейдя по ссылке:\r\n                                <a href=\"{{ConfirmationLink}}\">Подтвердить</a>\r\n                            </p>",
                            CreatedBy = new Guid("dc9aa449-3278-4816-aaf5-9257e39ff602"),
                            CreatedDate = new DateTime(2025, 9, 22, 6, 45, 28, 11, DateTimeKind.Utc).AddTicks(9152),
                            IsDeleted = false,
                            Name = "EC",
                            Subject = "Подтверждение регистрации",
                            UpdatedBy = new Guid("dc9aa449-3278-4816-aaf5-9257e39ff602"),
                            UpdatedDate = new DateTime(2025, 9, 22, 6, 45, 28, 11, DateTimeKind.Utc).AddTicks(9152)
                        });
                });

            modelBuilder.Entity("Partnerly.Models.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LogMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Logs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dcd670aa-3972-41ed-b718-fc68a292c289"),
                            Action = "UC",
                            CreatedBy = new Guid("dc9aa449-3278-4816-aaf5-9257e39ff602"),
                            CreatedDate = new DateTime(2025, 9, 22, 6, 45, 28, 11, DateTimeKind.Utc).AddTicks(9113),
                            IsDeleted = false,
                            LogMessage = "Created the Admin user from OnModelCreating",
                            Type = "I",
                            UpdatedBy = new Guid("dc9aa449-3278-4816-aaf5-9257e39ff602"),
                            UpdatedDate = new DateTime(2025, 9, 22, 6, 45, 28, 11, DateTimeKind.Utc).AddTicks(9113)
                        });
                });

            modelBuilder.Entity("Partnerly.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Partnerly.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4efbf269-476c-4a24-abf9-77d9bd019bb1"),
                            CreatedBy = new Guid("dc9aa449-3278-4816-aaf5-9257e39ff602"),
                            CreatedDate = new DateTime(2025, 9, 22, 6, 45, 28, 11, DateTimeKind.Utc).AddTicks(8952),
                            IsDeleted = false,
                            Name = "Administrator",
                            Type = "D",
                            UpdatedBy = new Guid("dc9aa449-3278-4816-aaf5-9257e39ff602"),
                            UpdatedDate = new DateTime(2025, 9, 22, 6, 45, 28, 11, DateTimeKind.Utc).AddTicks(8953)
                        },
                        new
                        {
                            Id = new Guid("34a008ff-2580-4126-b043-b84819ea7139"),
                            CreatedBy = new Guid("dc9aa449-3278-4816-aaf5-9257e39ff602"),
                            CreatedDate = new DateTime(2025, 9, 22, 6, 45, 28, 11, DateTimeKind.Utc).AddTicks(8958),
                            IsDeleted = false,
                            Name = "Employee",
                            Type = "U",
                            UpdatedBy = new Guid("dc9aa449-3278-4816-aaf5-9257e39ff602"),
                            UpdatedDate = new DateTime(2025, 9, 22, 6, 45, 28, 11, DateTimeKind.Utc).AddTicks(8959)
                        },
                        new
                        {
                            Id = new Guid("a9069bf5-2d6b-4bfa-bed8-0ca011c7346f"),
                            CreatedBy = new Guid("dc9aa449-3278-4816-aaf5-9257e39ff602"),
                            CreatedDate = new DateTime(2025, 9, 22, 6, 45, 28, 11, DateTimeKind.Utc).AddTicks(8960),
                            IsDeleted = false,
                            Name = "User",
                            Type = "V",
                            UpdatedBy = new Guid("dc9aa449-3278-4816-aaf5-9257e39ff602"),
                            UpdatedDate = new DateTime(2025, 9, 22, 6, 45, 28, 11, DateTimeKind.Utc).AddTicks(8961)
                        });
                });

            modelBuilder.Entity("Partnerly.Models.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid?>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmailConfirmationTokenExpiredAtHours")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = new Guid("dc9aa449-3278-4816-aaf5-9257e39ff602"),
                            CreatedDate = new DateTime(2025, 9, 22, 6, 45, 28, 11, DateTimeKind.Utc).AddTicks(9127),
                            EmailConfirmationTokenExpiredAtHours = 24,
                            IsDeleted = false,
                            UpdatedBy = new Guid("dc9aa449-3278-4816-aaf5-9257e39ff602"),
                            UpdatedDate = new DateTime(2025, 9, 22, 6, 45, 28, 11, DateTimeKind.Utc).AddTicks(9128)
                        });
                });

            modelBuilder.Entity("Partnerly.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Points")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Partnerly.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOnlayn")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastSignInDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MyReferralCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReferrerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoleId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReferrerId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc9aa449-3278-4816-aaf5-9257e39ff602"),
                            CreatedBy = new Guid("dc9aa449-3278-4816-aaf5-9257e39ff602"),
                            CreatedDate = new DateTime(2025, 9, 22, 6, 45, 28, 11, DateTimeKind.Utc).AddTicks(8660),
                            Email = "marat.iigservices@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Marat",
                            IsBlocked = false,
                            IsDeleted = false,
                            LastName = "Danielyan",
                            MyReferralCode = "BRANCH111",
                            PasswordHash = "$2a$11$mYttY3r80axkHK4znyLEi.GcCLMlX3GOgJ9/9bg8wQStQGQ4ibTzK",
                            Phone = "+37497111312",
                            RoleId = new Guid("4efbf269-476c-4a24-abf9-77d9bd019bb1"),
                            UpdatedBy = new Guid("dc9aa449-3278-4816-aaf5-9257e39ff602"),
                            UpdatedDate = new DateTime(2025, 9, 22, 6, 45, 28, 11, DateTimeKind.Utc).AddTicks(8666)
                        });
                });

            modelBuilder.Entity("Partnerly.Models.Payment", b =>
                {
                    b.HasOne("Partnerly.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Partnerly.Models.Transaction", b =>
                {
                    b.HasOne("Partnerly.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Partnerly.Models.User", b =>
                {
                    b.HasOne("Partnerly.Models.User", "Referrer")
                        .WithMany("Referrals")
                        .HasForeignKey("ReferrerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Partnerly.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Referrer");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Partnerly.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Partnerly.Models.User", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Referrals");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
