// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Partnerly.Models;

#nullable disable

namespace Partnerly.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250922130201_createdTheForgotPassword")]
    partial class createdTheForgotPassword
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Partnerly.Models.EmailAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EmailAttachments");
                });

            modelBuilder.Entity("Partnerly.Models.EmailConfirmationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid?>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Used")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UserId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("EmailConfirmationTokens");
                });

            modelBuilder.Entity("Partnerly.Models.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttachmentsMeta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyPlain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ed8de30-8917-4fde-b6fa-23d770172e1d"),
                            BodyHtml = "\r\n                            <h2>Здравствуйте, {{UserName}}!</h2>\r\n                            <p>\r\n                                Подтвердите ваш email, перейдя по ссылке:\r\n                                <a href=\"{{ConfirmationLink}}\">Подтвердить</a>\r\n                            </p>",
                            CreatedBy = new Guid("db925908-f3f1-4d0d-b326-8b2a8c97f106"),
                            CreatedDate = new DateTime(2025, 9, 22, 13, 2, 0, 652, DateTimeKind.Utc).AddTicks(1873),
                            IsDeleted = false,
                            Name = "EC",
                            Subject = "Подтверждение регистрации",
                            UpdatedBy = new Guid("db925908-f3f1-4d0d-b326-8b2a8c97f106"),
                            UpdatedDate = new DateTime(2025, 9, 22, 13, 2, 0, 652, DateTimeKind.Utc).AddTicks(1873)
                        },
                        new
                        {
                            Id = new Guid("1f397aa4-1f04-40d6-8b0d-74851bf29951"),
                            BodyHtml = "<h2>Здравствуйте, {{UserName}}!</h2>\r\n                                        <p>\r\n                                            Вы запросили сброс пароля для вашей учетной записи.  \r\n                                            Чтобы создать новый пароль, перейдите по ссылке ниже:\r\n                                        </p>\r\n                                        <p>\r\n                                            <a href=\"{ { ResetPasswordLink} }\r\n                                                    \" style=\"display: inline - block; padding: 10px 20px;\r\n                                                    background - color:#0d6efd;color:#fff;text-decoration:none;border-radius:5px;\">\r\n                                               Сбросить пароль\r\n                                            </ a >\r\n                                        </ p >\r\n                                        < p >\r\n                                            Если вы не запрашивали сброс пароля, просто проигнорируйте это письмо.\r\n                                        </p>",
                            CreatedBy = new Guid("db925908-f3f1-4d0d-b326-8b2a8c97f106"),
                            CreatedDate = new DateTime(2025, 9, 22, 13, 2, 0, 652, DateTimeKind.Utc).AddTicks(1883),
                            IsDeleted = false,
                            Name = "FP",
                            Subject = "Сброс пароля",
                            UpdatedBy = new Guid("db925908-f3f1-4d0d-b326-8b2a8c97f106"),
                            UpdatedDate = new DateTime(2025, 9, 22, 13, 2, 0, 652, DateTimeKind.Utc).AddTicks(1884)
                        });
                });

            modelBuilder.Entity("Partnerly.Models.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LogMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Logs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77b166db-cd93-4e80-99dc-59ee5e04f3f5"),
                            Action = "UC",
                            CreatedBy = new Guid("db925908-f3f1-4d0d-b326-8b2a8c97f106"),
                            CreatedDate = new DateTime(2025, 9, 22, 13, 2, 0, 652, DateTimeKind.Utc).AddTicks(1780),
                            IsDeleted = false,
                            LogMessage = "Created the Admin user from OnModelCreating",
                            Type = "I",
                            UpdatedBy = new Guid("db925908-f3f1-4d0d-b326-8b2a8c97f106"),
                            UpdatedDate = new DateTime(2025, 9, 22, 13, 2, 0, 652, DateTimeKind.Utc).AddTicks(1781)
                        });
                });

            modelBuilder.Entity("Partnerly.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Partnerly.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("690ed1c8-457e-4555-bca7-c9d2fe60a06f"),
                            CreatedBy = new Guid("db925908-f3f1-4d0d-b326-8b2a8c97f106"),
                            CreatedDate = new DateTime(2025, 9, 22, 13, 2, 0, 652, DateTimeKind.Utc).AddTicks(1582),
                            IsDeleted = false,
                            Name = "Administrator",
                            Type = "D",
                            UpdatedBy = new Guid("db925908-f3f1-4d0d-b326-8b2a8c97f106"),
                            UpdatedDate = new DateTime(2025, 9, 22, 13, 2, 0, 652, DateTimeKind.Utc).AddTicks(1583)
                        },
                        new
                        {
                            Id = new Guid("5a407f76-41a6-425e-85cd-f17d8e3a31f5"),
                            CreatedBy = new Guid("db925908-f3f1-4d0d-b326-8b2a8c97f106"),
                            CreatedDate = new DateTime(2025, 9, 22, 13, 2, 0, 652, DateTimeKind.Utc).AddTicks(1593),
                            IsDeleted = false,
                            Name = "Employee",
                            Type = "U",
                            UpdatedBy = new Guid("db925908-f3f1-4d0d-b326-8b2a8c97f106"),
                            UpdatedDate = new DateTime(2025, 9, 22, 13, 2, 0, 652, DateTimeKind.Utc).AddTicks(1593)
                        },
                        new
                        {
                            Id = new Guid("1737942c-cce1-4271-aa32-4704336edd6c"),
                            CreatedBy = new Guid("db925908-f3f1-4d0d-b326-8b2a8c97f106"),
                            CreatedDate = new DateTime(2025, 9, 22, 13, 2, 0, 652, DateTimeKind.Utc).AddTicks(1595),
                            IsDeleted = false,
                            Name = "User",
                            Type = "V",
                            UpdatedBy = new Guid("db925908-f3f1-4d0d-b326-8b2a8c97f106"),
                            UpdatedDate = new DateTime(2025, 9, 22, 13, 2, 0, 652, DateTimeKind.Utc).AddTicks(1595)
                        });
                });

            modelBuilder.Entity("Partnerly.Models.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid?>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmailConfirmationTokenExpiredAtHours")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("ForgotPasswordTokenExpiredAtHours")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = new Guid("db925908-f3f1-4d0d-b326-8b2a8c97f106"),
                            CreatedDate = new DateTime(2025, 9, 22, 13, 2, 0, 652, DateTimeKind.Utc).AddTicks(1797),
                            EmailConfirmationTokenExpiredAtHours = 24,
                            ForgotPasswordTokenExpiredAtHours = 1,
                            IsDeleted = false,
                            UpdatedBy = new Guid("db925908-f3f1-4d0d-b326-8b2a8c97f106"),
                            UpdatedDate = new DateTime(2025, 9, 22, 13, 2, 0, 652, DateTimeKind.Utc).AddTicks(1798)
                        });
                });

            modelBuilder.Entity("Partnerly.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Points")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Partnerly.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsOnlayn")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastSignInDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MyReferralCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReferrerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoleId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReferrerId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db925908-f3f1-4d0d-b326-8b2a8c97f106"),
                            CreatedBy = new Guid("db925908-f3f1-4d0d-b326-8b2a8c97f106"),
                            CreatedDate = new DateTime(2025, 9, 22, 13, 2, 0, 652, DateTimeKind.Utc).AddTicks(1354),
                            Email = "marat.iigservices@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Marat",
                            IsBlocked = false,
                            IsDeleted = false,
                            LastName = "Danielyan",
                            MyReferralCode = "BRANCH111",
                            PasswordHash = "$2a$11$CHagcWFBdOAqd051jphRF.NafXCb5CwoUmoD5O/bxhuu5XkgVdEUO",
                            Phone = "+37497111312",
                            RoleId = new Guid("690ed1c8-457e-4555-bca7-c9d2fe60a06f"),
                            UpdatedBy = new Guid("db925908-f3f1-4d0d-b326-8b2a8c97f106"),
                            UpdatedDate = new DateTime(2025, 9, 22, 13, 2, 0, 652, DateTimeKind.Utc).AddTicks(1359)
                        });
                });

            modelBuilder.Entity("Partnerly.Models.Payment", b =>
                {
                    b.HasOne("Partnerly.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Partnerly.Models.Transaction", b =>
                {
                    b.HasOne("Partnerly.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Partnerly.Models.User", b =>
                {
                    b.HasOne("Partnerly.Models.User", "Referrer")
                        .WithMany("Referrals")
                        .HasForeignKey("ReferrerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Partnerly.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Referrer");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Partnerly.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Partnerly.Models.User", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Referrals");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
